In [ ]:
# Numpy Library

In [1]:
import numpy as np

In [2]:
list1= [1, 2, 3, 4]


In [3]:
arr = np.array(list1)

In [4]:
arr

array([1, 2, 3, 4])

In [25]:
print(arr)

[1 2 3 4]


In [6]:
arr

array([1, 2, 3, 4])

In [7]:
print(arr)

[1 2 3 4]


In [8]:
list2= [1, 2, 3, 4, 7]
list3= [1, 4, 5, 2, 2]
list4= [1, 4, 4, 5, 6]

In [10]:
arr1= np.array([list2,list3,list4])

In [11]:
print(arr1)

[[1 2 3 4 7]
 [1 4 5 2 2]
 [1 4 4 5 6]]


In [13]:
arr1.shape

(3, 5)

In [14]:
# Indexing

In [15]:
arr1[:,:]

array([[1, 2, 3, 4, 7],
       [1, 4, 5, 2, 2],
       [1, 4, 4, 5, 6]])

In [16]:
arr1[0:2,:]

array([[1, 2, 3, 4, 7],
       [1, 4, 5, 2, 2]])

In [17]:
arr1[:,1:2]

array([[2],
       [4],
       [4]])

In [18]:
arr1.shape

(3, 5)

In [19]:
arr1[2:]= 100

In [20]:
print(arr1)

[[  1   2   3   4   7]
 [  1   4   5   2   2]
 [100 100 100 100 100]]


In [21]:
#some conditions for EDA(Exploratory data analysis)

In [22]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
arr1=np.arange(0,10).reshape(2,5)

In [28]:
arr2=np.arange(0,10).reshape(2,5)

In [29]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [30]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.ones((2,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
np.ones((2,5), dtype=float, order='c')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
#random distribution

In [34]:
np.random.rand(4,4)

array([[0.44433001, 0.21272468, 0.2878891 , 0.99020512],
       [0.89058189, 0.63670278, 0.34656139, 0.09692557],
       [0.64902253, 0.91566558, 0.97636118, 0.63509148],
       [0.98219169, 0.02439217, 0.11056608, 0.6394233 ]])

In [36]:
np.random.rand(5,5)

array([[0.35577954, 0.17402005, 0.77097742, 0.3616525 , 0.38907605],
       [0.75717761, 0.75102916, 0.47095018, 0.5633236 , 0.49871413],
       [0.05997096, 0.90770762, 0.96559654, 0.84290527, 0.38463384],
       [0.17276211, 0.39054947, 0.96832262, 0.83076066, 0.48466697],
       [0.94774334, 0.75898391, 0.76636137, 0.76855962, 0.75151636]])

In [37]:
np.random.rand(2,4)

array([[0.18614004, 0.58997123, 0.68762551, 0.413057  ],
       [0.94811513, 0.28020855, 0.48900639, 0.3962081 ]])

In [38]:
np.random.rand(1,2)

array([[0.36514969, 0.96938875]])